version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  proxy-manager:
    build:
      context: ./proxy-manager
    container_name: proxy-manager
    environment:
      DISABLE_IPV6: 'true'
    ports:
      - "8090:81"

volumes:
  postgres_data:
